       FUNCTION K38R(J,M,K,L,R, JA)
C BY NELSON WEIDERMAN
C TYPED BY AX FROM FORTRAN, 1.17.79
C
C RULE: DEFECT FOREVER AFTER THREE CONSECUTIVE
C DEFECTIONS BY OPPONENT
C JHIS STORES LAST THREE OPPONENT MOVES AS 4*J3 + 2*J2 +J1
C WHERE J1 IS MOST RECENT MOVE AND J3 IS LEAST RECENT
      k38r=ja    ! Added 7/27/93 to report own old value
      IF(M.NE.1) GO TO 10
      MOVE=0
      JHIS=0
   10 CONTINUE
      IF(MOVE.EQ.1) GO TO 20
      IF(JHIS.GE.4)JHIS=JHIS-4
      JHIS=JHIS*2
      JHIS=JHIS+J
      IF(JHIS.EQ.7)MOVE=1
   20 CONTINUE
      K38R=MOVE
      RETURN
      END
