      FUNCTION K54R(J,K,L,M,R,JA)
C BY WILLIAM H ROBERTSON
C TYPED BY JM
C AX ADD ST.999, 3/31/79
      INTEGER OPDEF,STDEF,COOPS
      LOGICAL OKDEF,MYDEF
      K54R=JA       ! Added 7/32/93 to report own old value
      K54R = 0
      IF (M .GT. 1) GOTO 5
C SET UP INITIAL CONDITIONS
      OPDEF = 0
      STDEF = 0
      DL = .20
      COOPS = 0
      OKDEF = .TRUE.
      MYDEF = .FALSE.
      NODEF = 0
      ND = 12
      RETURN
C LOWER DEFECTION LEVEL TO 10% ON MOVE 20
C SEE IF OPONENT DEFECTS
5     IF (M .EQ. 20) DL = .10
      IF (J .EQ. 1) GOTO 10
C OPONENT DOES NOT DEFECT
      STDEF = 0
      COOPS = COOPS + 1
      IF (FLOAT(OPDEF) .GT. FLOAT(M) * DL) GOTO 20
      IF (MOD(M,ND) .EQ. 0 .AND. OKDEF) GOTO 25
      MYDEF = .FALSE.
      RETURN
C OPONENT DEFECTS IN FIRST 4 MOVES
10    COOPS = 0
      IF (M .GT. 4) GOTO 15
      K54R = 1
      RETURN
C OPPONENT DEFECTS AFTER FIRST 4 MOVES.
C START TO KEEP TRACK OF NO. OF DEFECTIONS
15    STDEF = STDEF + 1
      OPDEF = OPDEF + 1
      IF (MYDEF) OKDEF = .FALSE.
      IF (FLOAT(OPDEF) .GT. FLOAT(M) * DL) GOTO 20
      IF (STDEF .GT. 2) GOTO 20
      MYDEF = .FALSE.
      RETURN
C OPPONENT DEFECTS EXCESSIVELY
20    IF (20 * OPDEF .LE. COOPS * M) RETURN
      K54R = 1
      MYDEF = .FALSE.
      RETURN
C PROGRAM WILL TRY A DEFECTON
25    K54R = 1
      MYDEF = .FALSE.
      NODEF = NODEF + 1
      IF (MOD(NODEF,6) .EQ. 0) ND = ND - 1
999   IF(ND .LT. 1) ND = 1
      RETURN
      END
